title: Muhammad Atef
logo: photo.jpg
description: A passionate data scientist with a professional certification from IBM, enthusiastic and self-motivated for the state of the art of the data science and machine learning fields, with experience executing data-driven solutions and ready to work in a big data environment, turns data using BI tools, machine learning, and deep learning into information and insights that lead to data-driven business insights and decisions.
theme: jekyll-theme-minimal
